before_install:
  - sudo apt-get update
  - sudo apt-get install -y golang

install: go get -u github.com/jeshuam/jbuild && go install github.com/jeshuam/jbuild
script: ${GO_PATH}/jbuild test //...
language: c++,
