before_install:
  - sudo apt-get update
  - sudo apt-get install -y golang

install: go get -u github.com/jeshuam/jbuild && go install github.com/jeshuam/jbuild
script: ${GOPATH}/bin/jbuild --external_repo_dir=/tmp/build/external --base_workspace_files=${GOPATH}/src/github.com/jeshuam/jbuild/cfg test //...
language: c++
